/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.nada

import de.huxhorn.sulky.ulid.ULID
import io.ktor.server.netty.EngineMain

fun main(args: Array<String>) {
    EngineMain.main(args)
}
val ulid: ULID = ULID()