apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: kafka-schema-backup
  namespace: default
  labels:
    team: aura
spec:
  image: {{ image }}
  port: 9090
  ingresses:
    - https://kafka-schema-backup.dev-gcp.nais.io
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 70
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 600m
      memory: 1024Mi
    requests:
      cpu: 300m
      memory: 384Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: kafka-schema-backup
        tier: db-f1-micro
        diskType: SSD
        highAvailability: true
        diskSize: 10
        diskAutoresize: true
        autoBackupTime: "03:00"
        cascadingDelete: false
