name: master

on:
  push:
    branches:
      - master

env:
  BASEIMAGE: docker.pkg.github.com/${{ github.repository }}/kafka-schema-backup

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v3.4.1
        with:
          java-version: '15'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Verify Gradle wrapper checksum
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
        run: ./gradlew test build
      - name: Lag tag for image
        run: echo "TAG=$(date +%Y%m%d%H%M%S)-$(git describe --always --dirty --exclude '*')" >> ${GITHUB_ENV}
      - name: Lag full image referanse
        id: declare
        run: |
          echo "IMAGE=${BASEIMAGE}:${TAG}" >> ${GITHUB_ENV}
          echo "::set-output name=image::${BASEIMAGE}:${TAG}"
      - name: Build docker image
        run: docker build -t ${IMAGE} .
      - name: Login to Github Package Registry
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Push Docker image
        run: docker push ${IMAGE}
    outputs:
      image: "${{ steps.declare.outputs.image }}"
  deploy-dev-gcp:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: nais/dev.yaml
  deploy-prod-gcp:
    name: Deploy to prod-gcp
    needs:
      - build
      - deploy-dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/nais.yml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: nais/prod.yaml