name: Test Pull Request

on: pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'temurin'
          cache: 'gradle'
        env:
          TESTCONTAINERS_RYUK_DISABLED: true

      - name: Verify Gradle wrapper checksum
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: ./gradlew clean build